// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmlgoQNHWBi7l9zZkoTBNWrLY54NghflY',
    appId: '1:970415359971:web:f4ca9c6621902e7f3502d6',
    messagingSenderId: '970415359971',
    projectId: 'phone-auth-a4bac',
    authDomain: 'phone-auth-a4bac.firebaseapp.com',
    storageBucket: 'phone-auth-a4bac.appspot.com',
    measurementId: 'G-S8RWFEVEC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB--r__tSNOobQCUGcZVg5BczSyquf8P_g',
    appId: '1:970415359971:android:17f861ac9863c35c3502d6',
    messagingSenderId: '970415359971',
    projectId: 'phone-auth-a4bac',
    storageBucket: 'phone-auth-a4bac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb4r0LrQbBjbGPTit8X9pouypXhzF9u8w',
    appId: '1:970415359971:ios:e18277ede1b428053502d6',
    messagingSenderId: '970415359971',
    projectId: 'phone-auth-a4bac',
    storageBucket: 'phone-auth-a4bac.appspot.com',
    iosBundleId: 'com.example.phoneAuthFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb4r0LrQbBjbGPTit8X9pouypXhzF9u8w',
    appId: '1:970415359971:ios:891721095e62ddb83502d6',
    messagingSenderId: '970415359971',
    projectId: 'phone-auth-a4bac',
    storageBucket: 'phone-auth-a4bac.appspot.com',
    iosBundleId: 'com.example.phoneAuthFirebase.RunnerTests',
  );
}
